
export const UPDATE_BOARD_STATE = "UPDATE_BOARD_STATE";

export const REST_BOARD_STATE = "REST_BOARD_STATE";

export const UPDATE_PIECE_NEXT_POSITION = "UPDATE_PIECE_NEXT_POSITION";

export const UPDATE_PIECE_COORDINATES = "UPDATE_PIECE_COORDINATES";

export const REST_BOARD_STATE_PIECES = "UPDATE_BOARD_STATE_PIECES";

export const UPDATE_BOARD_STATE_PIECES = "UPDATE_BOARD_STATE_PIECES";