
export const GET_PUBLIC_TOURNAMENTS_SUCCESS = "GET_PUBLIC_TOURNAMENTS_SUCCESS";
export const GET_PUBLIC_TOURNAMENTS_FAIL = "GET_PUBLIC_TOURNAMENTS_FAIL";

export const GET_CREATED_TOURNAMENT_SUCCESS = "GET_CREATED_TOURNAMENT_SUCCESS";
export const GET_CREATED_TOURNAMENT_FAIL = "GET_CREATED_TOURNAMENT_FAIL";

export const GET_REMOVED_TOURNEMENT_BY_ID_SUCCESS = "GET_REMOVED_TOURNEMENT_BY_ID_SUCCESS";
export const GET_REMOVED_TOURNEMENT_BY_ID_FAIL = "GET_CREATED_TOURNAMENT_FAIL";

export const GET_TOURNAMENT_BY_ID_SUCCESS = "GET_TOURNAMENT_BY_ID_SUCCESS";
export const GET_TOURNAMENT_BY_ID_FAIL = "GET_TOURNAMENT_BY_ID_FAIL";