export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_UPDATED_USER_STATUS_SUCCESS = "GET_UPDATED_USER_STATUS_SUCCESS";
export const GET_UPDATED_USER_STATUS_FAIL = "GET_UPDATED_USER_STATUS_FAIL";

export const GET_PUBLIC_USERS_SUCCESS = "GET_PUBLIC_USERS_SUCCESS";
export const GET_PUBLIC_USERS_FAIL = "GET_PUBLIC_USERS_FAIL";


export const GET_PUBLIC_USERS_BY_ID_SUCCESS = "GET_PUBLIC_USERS_BY_ID_SUCCESS";
export const GET_PUBLIC_USERS_BY_ID_FAIL = "GET_PUBLIC_USERS_BY_ID_FAIL";


export const GET_ADD_USER_SUCCESS = "GET_ADD_USER_SUCCESS";
export const GET_ADD_USER_FAIL = "GET_ADD_USER_FAIL";

export const GET_REMOVE_USER_SUCCESS = "GET_REMOVE_USER_SUCCESS";
export const GET_REMOVE_USER_FAIL = "GET_REMOVE_USER_FAIL";

export const GET_CONNECTED_USERS_SUCCESS = "GET_CONNECTED_USERS_SUCCESS";
export const GET_CONNECTED_USERS_FAIL = "GET_CONNECTED_USERS_FAIL";